// <auto-generated />
namespace Nofy.EntityFramework6.Migrations
{
	using System.CodeDom.Compiler;
	using System.Data.Entity.Migrations.Infrastructure;
	using System.Resources;

	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061138245_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
